2025-05-16 14:00:15,922 | ERROR    | server | Exception on /login [GET]
Traceback (most recent call last):
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\server.py", line 285, in login
    return render_template('login.html', title='Вход',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\templates\base.html", line 60, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\templates\login.html", line 25, in block 'content'
    {{ form.captcha_token }}
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\markupsafe\__init__.py", line 43, in escape
    return Markup(s.__html__())
                  ^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\wtforms\fields\core.py", line 148, in __html__
    return self()
           ^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\wtforms\fields\core.py", line 164, in __call__
    return self.meta.render_field(self, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\wtforms\meta.py", line 64, in render_field
    return field.widget(field, **render_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Maksim\Desktop\maksim\ЯЛ\PyGame\EduCred_YANDEX_MYWEB\.venv\Lib\site-packages\wtforms\widgets\core.py", line 178, in __call__
    input_params = self.html_params(name=field.name, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: wtforms.widgets.core.html_params() got multiple values for keyword argument 'name'
2025-05-16 14:03:31,922 | ERROR    | server | An error occurred: 'LoginForm' object has no attribute 'captcha_token'
2025-05-16 14:03:46,129 | ERROR    | server | An error occurred: 'LoginForm' object has no attribute 'captcha_token'
2025-05-16 17:09:04,588 | ERROR    | server | An error occurred: 'AnonymousUserMixin' object has no attribute 'id'
2025-05-16 17:09:11,169 | ERROR    | server | An error occurred: 'AnonymousUserMixin' object has no attribute 'id'
2025-05-16 17:09:37,637 | ERROR    | server | An error occurred: 'AnonymousUserMixin' object has no attribute 'id'
2025-05-16 17:09:53,639 | ERROR    | server | An error occurred: 'AnonymousUserMixin' object has no attribute 'id'
2025-05-18 15:14:04,874 | ERROR    | server | (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-18 15:14:59,446 | ERROR    | server | (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-18 15:15:29,218 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 12:09:55,228 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 12:10:12,777 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 12:11:07,735 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 12:12:54,859 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 12:18:52,151 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 12:32:08,625 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 12:35:30,633 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 12:41:52,687 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 12:42:03,821 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:11:19,385 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:17:44,643 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:20:06,070 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:20:43,002 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:20:53,153 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:21:36,841 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:25:12,487 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:25:24,750 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:25:34,615 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:25:59,260 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
2025-05-25 13:36:25,750 | ERROR    | server | Allow access due to an error: code=403; message={"status":"failed","message":"Authentication failed. Invalid secret."}
